name: Bug report
description: Create a report to help us improve.
title: "bixaluswds - bug: [YOUR_TITLE]"
labels: ["bug"]

body:
  - type: textarea
    id: issue
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
  - type: textarea
    id: system
    attributes:
      label: System information
      placeholder: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem.
